### ISSUE TITLE
파싱 배치를 돌리는 과정에서 JPA could not initialize proxy - no Session 발생

### ISSUE THREAD

**Issue by k4keye** [k4keye/VisitKnowledge#4]
주기적으로 배치파일을 통해
사이트들을 탐색하여 자료를 모두 획득한후에
해당 자료가 이미 디비에 존재하는지 체크하는 과정에서 발생

```
to lazily initialize a collection of role: com.birariro.dailydevblogassemble.domain.library.Library.documents, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:614)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:218)
	at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:162)
	at org.hibernate.collection.internal.PersistentBag.size(PersistentBag.java:371)
```

**Comment by k4keye** [comment]
배치에 동작시킬떄의 청크 사이즈의 문제였다.
청크 문제가 게속 발생하고있어 빨리 해결할 필요가있음.

**Comment by k4keye** [comment]
Reader 를 pageing 이 가능한 JpaPagingItemReader 로 변경
하여 해결

```
private final int chunkSize = 10;
@Bean
public Step libraryDocumentParsingStep(){
    return stepBuilderFactory.get("libraryDocumentParsingStep")
            .<Library, Library> chunk(chunkSize)
            .reader(libraryDocumentParsingReader())
            ..생략
}

  @Bean
  @StepScope
  public JpaPagingItemReader<Library> libraryDocumentParsingReader(){

      return new JpaPagingItemReaderBuilder<Library>()
              .queryString("select l from Library l where l.entityState = 'ACTIVE'")
              .pageSize(chunkSize)
              .entityManagerFactory(entityManagerFactory)
              .name("libraryPagingReader")
              .build();
  }
```
